name: travel_blog
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  flutter_riverpod: ^1.0.4
  flutter_svg: ^1.1.3
  flutter_native_splash: ^2.2.7
  share_plus: ^4.0.10+1
  intl: ^0.17.0
  url_launcher: ^6.1.5
  flutter_local_notifications: ^9.7.1
  location: ^4.4.0
  json_serializable: ^6.3.1
  equatable: ^2.0.3
  image_picker: ^0.8.5+3
  carousel_slider: ^4.1.1
  shimmer: ^2.0.0
  hive: ^2.2.3
  fluro: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/
 
  fonts:
    - family: SansRegular
      fonts:
        - asset: assets/fonts/PTSans-Regular.ttf

    - family: SansBold
      fonts:
        - asset: assets/fonts/PTSans-Bold.ttf

    - family: SansItalic
      fonts:
        - asset: assets/fonts/PTSans-Italic.ttf
    
    - family: SansBoldItalic
      fonts:
        - asset: assets/fonts/PTSans-BoldItalic.ttf
  
